version: '3.4'

services:
  keycloak-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8080
    environment:
      - APPLICATION_URL=http://localhost:8080
    command:
      - "-b 0.0.0.0"
    volumes:
      - ./themes/store:/opt/jboss/keycloak/themes/store
